apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.3.x # Versi stabil
    helm:
      parameters:
        - name: service.type
          value: NodePort
        - name: service.nodePort
          value: "30001" # Kita buka di port 30001
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true # ArgoCD akan membuat namespace 'monitoring' otomatis
